name: 'Build'

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ main ]
  workflow_dispatch:

jobs:
  CheckStaticContent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Markdown lint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          args: "README.md"
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Try build container
        shell: bash
        run: |
          sudo docker build -t graphics-test-image -f ./Dockerfile .
          sudo docker rmi $(docker images "{{.Repository}}:{{.Tag}}" | grep 'graphics-test-image')
  BuildContainer:
    runs-on: ubuntu-latest
    needs: [CheckStaticContent, Build]
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/grillbot/grillbot-graphics:main
  DeployToProduction:
    runs-on: ubuntu-latest
    environment: 'Production'
    needs: BuildContainer
    if: github.ref == 'refs/head/master'
    steps:
      - name: Execute deployment on SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_Username }}
          password: ${{ secrets.SSH_Password }}
          port: 22
          script:
            echo '${{ secrets.SSH_Password }}' | sudo -S /scripts/podman-reload.py grillbot-graphics

